[platformio]
boards_dir = boards

[env:esp32-3248S035C]
platform = espressif32
board = esp32-3248S035C
framework = arduino
lib_deps =
    git+https://github.com/rzeldent/esp32-smartdisplay#2.1.0
    gin66/FastAccelStepper@^1.2.5

build_flags =
    -I src
    -D LV_CONF_PATH="\"${PROJECT_DIR}/src/lv_conf.h\""

monitor_speed = 115200
